
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srgpueaknceplhtquhcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyZ3B1ZWFrbmNlcGxodHF1aGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMTQ0MjMsImV4cCI6MjA1NDc5MDQyM30.loZv5zrKM51DAtgBBQy6XzMReyJaGy7nO96cn3En-SE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true
  },
  global: {
    fetch: (url, options) => fetch(url, options)
  }
});

// Setup a scheduled function to mark ended events as finished
(async () => {
  try {
    const { error } = await supabase.rpc('delete_expired_events');
    if (error) console.error('Error marking events finished:', error);
  } catch (e) {
    console.error('Could not run delete_expired_events function:', e);
  }
})();
